version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR aem-base..........
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 077344799555.dkr.ecr.us-east-1.amazonaws.com
      - docker login --username="sreejani" --password="godisgreat@123"
  build:
    commands:
      - echo Build started on `date`
      - cd aem-base_image
      - echo Building the Docker image......   
      - docker build -t aem-base-image .
      - docker tag aem-base-image:latest 077344799555.dkr.ecr.us-east-1.amazonaws.com/aem-base-image:latest      
      - docker push 077344799555.dkr.ecr.us-east-1.amazonaws.com/aem-base-image:latest
      
#      - aws ecr batch-delete-image --repository-name aem-base-image --image-ids imageTag=version
      
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image....
#       - cd ..
#       - cd aem-author
#       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 077344799555.dkr.ecr.us-east-1.amazonaws.com
#       - docker login --username="sreejani" --password="godisgreat@123"
#       - docker rmi --force aem-author
#       - docker build -t aem-author .      
#       - docker tag aem-author:latest 077344799555.dkr.ecr.us-east-1.amazonaws.com/aem-author:latest
#       - docker images
#       - docker push 077344799555.dkr.ecr.us-east-1.amazonaws.com/aem-author:latest
      
