version: 0.2

phases:
  pre_build:
    commands:
     
      - ls -ltr
      - aws s3 cp aem-folder.zip s3://aem-bkt-terr-nvir/aem-folder.zip
      
  build:
    commands:
      - echo Build started on `date`
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 077344799555.dkr.ecr.us-east-1.amazonaws.com
      - docker login --username="sreejani" --password="godisgreat@123"
      - aws s3 cp s3://aem-bkt-terr-nvir/aem-folder.zip aem-install.zip
      - ls -ltr
      - sudo apt-get update
      - sudo apt install -y p7zip-full p7zip-rar
#       - fastjar xvf aem-install.zip
      - 7z x aem-install.zip
      - ls -ltr
      - cd aem-installfixed
      - cd aem-base_image
      - echo Building the Docker image......   
      - docker build -t aem-base-image .
      #- docker tag aem-base-image:latest 077344799555.dkr.ecr.us-east-1.amazonaws.com/aem-base-image:latest      
      #- docker push 077344799555.dkr.ecr.us-east-1.amazonaws.com/aem-base-image:latest
      - docker images
      - cd ..
      - cd aem-author
      - docker build -t aem-author .
      - docker images
      #- docker run -p 4502:4502 aem-author
      #- curl http://localhost:4502
      - docker tag aem-author:latest 077344799555.dkr.ecr.us-east-1.amazonaws.com/aem-author:latest
      
  post_build:
     commands:
       - echo Build completed on `date`
       - echo Pushing the Docker image....
#      - cd ..
#      - cd aem-author
       - docker push 077344799555.dkr.ecr.us-east-1.amazonaws.com/aem-author:latest
        
