version: 0.2
env:
  git-credential-helper: yes
phases:
  pre_build:
    commands:

  build:
    commands:
      #- cd eks-terr-cicd-AEMbase
      - echo Build started on `date`
# #       - sudo apt install unzip
# #       - unzip -q aem-zip
#       - git clone https://github.com/sreejanigit/eks-terr-cicd-AEMbase/archive/master.zip
#       - ls -ltr
#       - cd eks-terr-cicd-AEMbase
#       - file aem-zip.zip
#       - sha256sum aem-zip.zip
#       - cd aem-zip
#       - ls -ltr
      - curl -OJL https://github.com/git-lfs/git-lfs/releases/download/v2.13.2/git-lfs-linux-amd64-v2.13.2.tar.gz
      - ls -ltr
      - tar xzf git-lfs-linux-amd64-v2.13.2.tar.gz
      - ./install.sh
      - git lfs install
      - git remote add aem https://github.com/sreejanigit/eks-terr-cicd-AEMbase.git
      - git lfs pull 
      - cd eks-terr-cicd-AEMbase
      - cd aem-base_image
      - echo Building the Docker image......   
      - docker build -t aem-base-image .
      #- docker tag aem-base-image:latest 077344799555.dkr.ecr.us-east-1.amazonaws.com/aem-base-image:latest      
      #- docker push 077344799555.dkr.ecr.us-east-1.amazonaws.com/aem-base-image:latest
      - docker images
      - cd ..
      - cd aem-author
      - docker build -t aem-author .
      - docker images
      #- docker run -p 4502:4502 aem-author
      #- curl http://localhost:4502
      - docker tag aem-author:latest 077344799555.dkr.ecr.us-east-1.amazonaws.com/aem-author:latest
  post_build:
     commands:
       - echo Build completed on `date`
       - echo Pushing the Docker image....
#      - cd ..
#      - cd aem-author
       - docker push 077344799555.dkr.ecr.us-east-1.amazonaws.com/aem-author:latest
        
