version: 0.2

phases:
  pre_build:
    commands:
      - echo Creating Namespace...
      - kubectl create namespace eks-sample-app
  build:
    commands:
      - echo Build started on `date`
      - cd manifests
      - kubectl apply -f eks-sample-deployment.yaml
      - kubectl apply -f eks-sample-service.yaml
  post_build:
    commands:
      - echo Build completed on `date`
